FROM python:3.7-slim

WORKDIR /app

ADD . /app

RUN sudo apt-get update

RUN ImportError: libGL.so.1: cannot open shared object file: No such file or directory


RUN pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 5000

ENV NAME OpentoAll

CMD ["python","app.py"]
